# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/mb_subsystem/mb_subsystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem || ORIG_REF_NAME==mb_subsystem} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_v10_0 || ORIG_REF_NAME==mb_subsystem_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_1/mb_subsystem_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_v10_1 || ORIG_REF_NAME==mb_subsystem_ilmb_v10_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_1/mb_subsystem_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_periph_0/mb_subsystem_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_xlconcat_0/mb_subsystem_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mdm_1_0 || ORIG_REF_NAME==mb_subsystem_mdm_1_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_proc_sys_reset_1_0/mb_subsystem_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_proc_sys_reset_1_0 || ORIG_REF_NAME==mb_subsystem_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_timer_0_0 || ORIG_REF_NAME==mb_subsystem_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_0/mb_subsystem_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mb_subsystem_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/mb_subsystem_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_0} -quiet] -quiet

# Block Designs: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/bd_1ed2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2 || ORIG_REF_NAME==bd_1ed2} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1ed2_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_eth_buf_0 || ORIG_REF_NAME==bd_1ed2_eth_buf_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/bd_1ed2_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_mac_0 || ORIG_REF_NAME==bd_1ed2_mac_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_2/bd_1ed2_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_c_shift_ram_0_0 || ORIG_REF_NAME==bd_1ed2_c_shift_ram_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_3/bd_1ed2_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_c_counter_binary_0_0 || ORIG_REF_NAME==bd_1ed2_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_4/bd_1ed2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_xlconstant_0_0 || ORIG_REF_NAME==bd_1ed2_xlconstant_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_5/bd_1ed2_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_util_vector_logic_0_0 || ORIG_REF_NAME==bd_1ed2_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_dma_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_dma_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_2/mb_subsystem_clk_wiz_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_0_2 || ORIG_REF_NAME==mb_subsystem_clk_wiz_0_2} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_1_0/mb_subsystem_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_1_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_selectio_wiz_0_0/mb_subsystem_selectio_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_selectio_wiz_0_0 || ORIG_REF_NAME==mb_subsystem_selectio_wiz_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_fifo_mm_s_0_0/mb_subsystem_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==mb_subsystem_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_DIFF_To_single_0_0/mb_subsystem_DIFF_To_single_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_DIFF_To_single_0_0 || ORIG_REF_NAME==mb_subsystem_DIFF_To_single_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_TX_SERIALIZER_0/mb_subsystem_TX_SERIALIZER_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_TX_SERIALIZER_0 || ORIG_REF_NAME==mb_subsystem_TX_SERIALIZER_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_1/mb_subsystem_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_1 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_0/mb_subsystem_axi_clock_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_clock_converter_0_0 || ORIG_REF_NAME==mb_subsystem_axi_clock_converter_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axis_clock_converter_0_1/mb_subsystem_axis_clock_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axis_clock_converter_0_1 || ORIG_REF_NAME==mb_subsystem_axis_clock_converter_0_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_xlconstant_0_0/mb_subsystem_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xlconstant_0_0 || ORIG_REF_NAME==mb_subsystem_xlconstant_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axis_clock_converter_0_0/mb_subsystem_axis_clock_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axis_clock_converter_0_0 || ORIG_REF_NAME==mb_subsystem_axis_clock_converter_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_AP_Generator_0_0/mb_subsystem_AP_Generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_AP_Generator_0_0 || ORIG_REF_NAME==mb_subsystem_AP_Generator_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_xlslice_0_0/mb_subsystem_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xlslice_0_0 || ORIG_REF_NAME==mb_subsystem_xlslice_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_bitslip_Generator_0_0/mb_subsystem_bitslip_Generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_bitslip_Generator_0_0 || ORIG_REF_NAME==mb_subsystem_bitslip_Generator_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_inverse_reverse_0_0/mb_subsystem_inverse_reverse_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_inverse_reverse_0_0 || ORIG_REF_NAME==mb_subsystem_inverse_reverse_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_2/mb_subsystem_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_2 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_3/mb_subsystem_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_3 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_3} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_2/mb_subsystem_axi_clock_converter_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_clock_converter_0_2 || ORIG_REF_NAME==mb_subsystem_axi_clock_converter_0_2} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_1/mb_subsystem_axi_clock_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_clock_converter_0_1 || ORIG_REF_NAME==mb_subsystem_axi_clock_converter_0_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_inverse_reverse_0_1/mb_subsystem_inverse_reverse_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_inverse_reverse_0_1 || ORIG_REF_NAME==mb_subsystem_inverse_reverse_0_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_4/mb_subsystem_axi_clock_converter_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_clock_converter_0_4 || ORIG_REF_NAME==mb_subsystem_axi_clock_converter_0_4} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_TX_invert_1/mb_subsystem_TX_invert_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_TX_invert_1 || ORIG_REF_NAME==mb_subsystem_TX_invert_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_3/mb_subsystem_axi_clock_converter_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_clock_converter_0_3 || ORIG_REF_NAME==mb_subsystem_axi_clock_converter_0_3} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_TX_invert_0/mb_subsystem_TX_invert_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_TX_invert_0 || ORIG_REF_NAME==mb_subsystem_TX_invert_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_rst_clk_wiz_0_125M_0/mb_subsystem_rst_clk_wiz_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==mb_subsystem_rst_clk_wiz_0_125M_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_S_to_diff_0_0/mb_subsystem_S_to_diff_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_S_to_diff_0_0 || ORIG_REF_NAME==mb_subsystem_S_to_diff_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_S_to_diff_0_1/mb_subsystem_S_to_diff_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_S_to_diff_0_1 || ORIG_REF_NAME==mb_subsystem_S_to_diff_0_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_F1_F2_FILTER_0_0/mb_subsystem_F1_F2_FILTER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_F1_F2_FILTER_0_0 || ORIG_REF_NAME==mb_subsystem_F1_F2_FILTER_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_0/mb_subsystem_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_0 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_ila_0_1/mb_subsystem_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ila_0_1 || ORIG_REF_NAME==mb_subsystem_ila_0_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_iic_0_0/mb_subsystem_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_iic_0_0 || ORIG_REF_NAME==mb_subsystem_axi_iic_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_mem_intercon_0/mb_subsystem_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_mem_intercon_0 || ORIG_REF_NAME==mb_subsystem_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_blk_mem_gen_0_0/mb_subsystem_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_blk_mem_gen_0_0 || ORIG_REF_NAME==mb_subsystem_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_lmb_bram_1/mb_subsystem_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_lmb_bram_1 || ORIG_REF_NAME==mb_subsystem_lmb_bram_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_xbar_1/mb_subsystem_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xbar_1 || ORIG_REF_NAME==mb_subsystem_xbar_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xbar_0 || ORIG_REF_NAME==mb_subsystem_xbar_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_m01_regslice_0/mb_subsystem_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_m01_regslice_0 || ORIG_REF_NAME==mb_subsystem_m01_regslice_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_m00_regslice_0/mb_subsystem_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_m00_regslice_0 || ORIG_REF_NAME==mb_subsystem_m00_regslice_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_s04_regslice_0/mb_subsystem_s04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s04_regslice_0 || ORIG_REF_NAME==mb_subsystem_s04_regslice_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_s04_data_fifo_0/mb_subsystem_s04_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s04_data_fifo_0 || ORIG_REF_NAME==mb_subsystem_s04_data_fifo_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_s03_regslice_0/mb_subsystem_s03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s03_regslice_0 || ORIG_REF_NAME==mb_subsystem_s03_regslice_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_s03_data_fifo_0/mb_subsystem_s03_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s03_data_fifo_0 || ORIG_REF_NAME==mb_subsystem_s03_data_fifo_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_s02_regslice_0/mb_subsystem_s02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s02_regslice_0 || ORIG_REF_NAME==mb_subsystem_s02_regslice_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_s02_data_fifo_0/mb_subsystem_s02_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s02_data_fifo_0 || ORIG_REF_NAME==mb_subsystem_s02_data_fifo_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_s01_regslice_0/mb_subsystem_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s01_regslice_0 || ORIG_REF_NAME==mb_subsystem_s01_regslice_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_s01_data_fifo_0/mb_subsystem_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s01_data_fifo_0 || ORIG_REF_NAME==mb_subsystem_s01_data_fifo_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_s00_regslice_0/mb_subsystem_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s00_regslice_0 || ORIG_REF_NAME==mb_subsystem_s00_regslice_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_s00_data_fifo_0/mb_subsystem_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_s00_data_fifo_0 || ORIG_REF_NAME==mb_subsystem_s00_data_fifo_0} -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0_ooc_debug.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/constraints/mb_subsystem_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0} -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/constraints/mb_subsystem_mig_7series_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0} -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_v10_0 || ORIG_REF_NAME==mb_subsystem_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_1/mb_subsystem_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_v10_1 || ORIG_REF_NAME==mb_subsystem_ilmb_v10_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_1/mb_subsystem_ilmb_v10_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_1/mb_subsystem_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_mdm_1_0 || ORIG_REF_NAME==mb_subsystem_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0_ooc_trace.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_proc_sys_reset_1_0/mb_subsystem_proc_sys_reset_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_proc_sys_reset_1_0 || ORIG_REF_NAME==mb_subsystem_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_proc_sys_reset_1_0/mb_subsystem_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_proc_sys_reset_1_0 || ORIG_REF_NAME==mb_subsystem_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_proc_sys_reset_1_0/mb_subsystem_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_timer_0_0 || ORIG_REF_NAME==mb_subsystem_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_0/mb_subsystem_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1ed2_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1ed2_eth_buf_0 || ORIG_REF_NAME==bd_1ed2_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_1ed2_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1ed2_eth_buf_0 || ORIG_REF_NAME==bd_1ed2_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1ed2_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1ed2_mac_0 || ORIG_REF_NAME==bd_1ed2_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1ed2_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1ed2_mac_0 || ORIG_REF_NAME==bd_1ed2_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1ed2_mac_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1ed2_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1ed2_mac_0 || ORIG_REF_NAME==bd_1ed2_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/bd_1ed2_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/mb_subsystem_axi_ethernet_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/synth/mb_subsystem_axi_ethernet_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_dma_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_dma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_dma_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_dma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_2/mb_subsystem_clk_wiz_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_0_2 || ORIG_REF_NAME==mb_subsystem_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_2/mb_subsystem_clk_wiz_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_0_2 || ORIG_REF_NAME==mb_subsystem_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_0_2/mb_subsystem_clk_wiz_0_2_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_1_0/mb_subsystem_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_1_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_1_0/mb_subsystem_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_clk_wiz_1_0 || ORIG_REF_NAME==mb_subsystem_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_clk_wiz_1_0/mb_subsystem_clk_wiz_1_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_selectio_wiz_0_0/mb_subsystem_selectio_wiz_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_selectio_wiz_0_0/mb_subsystem_selectio_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_selectio_wiz_0_0 || ORIG_REF_NAME==mb_subsystem_selectio_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_fifo_mm_s_0_0/mb_subsystem_axi_fifo_mm_s_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_TX_SERIALIZER_0/mb_subsystem_TX_SERIALIZER_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_TX_SERIALIZER_0/mb_subsystem_TX_SERIALIZER_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_TX_SERIALIZER_0 || ORIG_REF_NAME==mb_subsystem_TX_SERIALIZER_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_1/mb_subsystem_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_1 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_1/mb_subsystem_axi_gpio_0_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_1/mb_subsystem_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_1 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_0/mb_subsystem_axi_clock_converter_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_clock_converter_0_0 || ORIG_REF_NAME==mb_subsystem_axi_clock_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_0/mb_subsystem_axi_clock_converter_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axis_clock_converter_0_1/mb_subsystem_axis_clock_converter_0_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axis_clock_converter_0_1/mb_subsystem_axis_clock_converter_0_1/mb_subsystem_axis_clock_converter_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axis_clock_converter_0_1 || ORIG_REF_NAME==mb_subsystem_axis_clock_converter_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axis_clock_converter_0_1/mb_subsystem_axis_clock_converter_0_1/mb_subsystem_axis_clock_converter_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axis_clock_converter_0_1 || ORIG_REF_NAME==mb_subsystem_axis_clock_converter_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axis_clock_converter_0_0/mb_subsystem_axis_clock_converter_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axis_clock_converter_0_0/mb_subsystem_axis_clock_converter_0_0/mb_subsystem_axis_clock_converter_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axis_clock_converter_0_0 || ORIG_REF_NAME==mb_subsystem_axis_clock_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axis_clock_converter_0_0/mb_subsystem_axis_clock_converter_0_0/mb_subsystem_axis_clock_converter_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axis_clock_converter_0_0 || ORIG_REF_NAME==mb_subsystem_axis_clock_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_2/mb_subsystem_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_2 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_2/mb_subsystem_axi_gpio_0_2_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_2/mb_subsystem_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_2 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_3/mb_subsystem_axi_gpio_0_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_3 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_3/mb_subsystem_axi_gpio_0_3_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_3/mb_subsystem_axi_gpio_0_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_3 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_2/mb_subsystem_axi_clock_converter_0_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_clock_converter_0_2 || ORIG_REF_NAME==mb_subsystem_axi_clock_converter_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_2/mb_subsystem_axi_clock_converter_0_2_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_1/mb_subsystem_axi_clock_converter_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_clock_converter_0_1 || ORIG_REF_NAME==mb_subsystem_axi_clock_converter_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_1/mb_subsystem_axi_clock_converter_0_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_4/mb_subsystem_axi_clock_converter_0_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_clock_converter_0_4 || ORIG_REF_NAME==mb_subsystem_axi_clock_converter_0_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_4/mb_subsystem_axi_clock_converter_0_4_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_TX_invert_1/mb_subsystem_TX_invert_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_TX_invert_1 || ORIG_REF_NAME==mb_subsystem_TX_invert_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_TX_invert_1/mb_subsystem_TX_invert_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_TX_invert_1/mb_subsystem_TX_invert_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_TX_invert_1 || ORIG_REF_NAME==mb_subsystem_TX_invert_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_3/mb_subsystem_axi_clock_converter_0_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_clock_converter_0_3 || ORIG_REF_NAME==mb_subsystem_axi_clock_converter_0_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_clock_converter_0_3/mb_subsystem_axi_clock_converter_0_3_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_TX_invert_0/mb_subsystem_TX_invert_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_TX_invert_0 || ORIG_REF_NAME==mb_subsystem_TX_invert_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_TX_invert_0/mb_subsystem_TX_invert_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_TX_invert_0/mb_subsystem_TX_invert_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_TX_invert_0 || ORIG_REF_NAME==mb_subsystem_TX_invert_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_rst_clk_wiz_0_125M_0/mb_subsystem_rst_clk_wiz_0_125M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==mb_subsystem_rst_clk_wiz_0_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_rst_clk_wiz_0_125M_0/mb_subsystem_rst_clk_wiz_0_125M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==mb_subsystem_rst_clk_wiz_0_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_rst_clk_wiz_0_125M_0/mb_subsystem_rst_clk_wiz_0_125M_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_0/mb_subsystem_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_0 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_0/mb_subsystem_axi_gpio_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_0/mb_subsystem_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_0 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_ila_0_1 || ORIG_REF_NAME==mb_subsystem_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_ila_0_1/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_ila_0_1 || ORIG_REF_NAME==mb_subsystem_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_ila_0_1/mb_subsystem_ila_0_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_iic_0_0/mb_subsystem_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_iic_0_0 || ORIG_REF_NAME==mb_subsystem_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_subsystem/ip/mb_subsystem_axi_iic_0_0/mb_subsystem_axi_iic_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_blk_mem_gen_0_0/mb_subsystem_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_lmb_bram_1/mb_subsystem_lmb_bram_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_xbar_1/mb_subsystem_xbar_1_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_m01_regslice_0/mb_subsystem_m01_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_m00_regslice_0/mb_subsystem_m00_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s04_regslice_0/mb_subsystem_s04_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s04_data_fifo_0/mb_subsystem_s04_data_fifo_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s03_regslice_0/mb_subsystem_s03_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s03_data_fifo_0/mb_subsystem_s03_data_fifo_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s02_regslice_0/mb_subsystem_s02_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s02_data_fifo_0/mb_subsystem_s02_data_fifo_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s01_regslice_0/mb_subsystem_s01_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s01_data_fifo_0/mb_subsystem_s01_data_fifo_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s00_regslice_0/mb_subsystem_s00_regslice_0_ooc.xdc

# XDC: bd/mb_subsystem/ip/mb_subsystem_s00_data_fifo_0/mb_subsystem_s00_data_fifo_0_ooc.xdc

# XDC: bd/mb_subsystem/mb_subsystem_ooc.xdc
