webtalk_init -webtalk_dir F:\\XAPP1026\\KC705_AxiEth_150MHZ_64KB\\vfat3_firmware\\HW\\project_vbv3b\\project_vbv3b.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-04-17 16:43:10" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174122087_174122088_210655991_749" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "m5jqbc93591chmoas2ro75o8a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.055 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1523958618337" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key Arch -value "kintex7" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key Device -value "7k325t" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1523958618337"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1523976189988"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1523976189988"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1523976189988"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1523976189988"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1523976189988"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1523976189988"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1523976189988"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1523976189988"
webtalk_transmit -clientid 485422923 -regid "174122087_174122088_210655991_749" -xml F:\\XAPP1026\\KC705_AxiEth_150MHZ_64KB\\vfat3_firmware\\HW\\project_vbv3b\\project_vbv3b.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\XAPP1026\\KC705_AxiEth_150MHZ_64KB\\vfat3_firmware\\HW\\project_vbv3b\\project_vbv3b.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\XAPP1026\\KC705_AxiEth_150MHZ_64KB\\vfat3_firmware\\HW\\project_vbv3b\\project_vbv3b.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
